name: Release Published

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-zip-perl
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode keystore
        continue-on-error: true
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.SIGNING_STORE_BASE64 }}
          filename: "app/keystore.jks"
      - name: Build with Gradle (minified)
        run: rm -f app/keystore.jks && ./gradlew ":app:assembleRelease" -Pxposed=true --no-daemon
        env:
          BUILD_RELEASE_MINIFYENABLED: true
          GRADLE_OPTS: -Xmx2048m
          JAVA_TOOL_OPTIONS: -Xmx6g
      - name: Upload APK to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} app/build/outputs/apk/release/*.apk --repo ${{ github.repository }}
      - name: Upload Mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: app/build/outputs/mapping/release/mapping.txt
